Autenticaçao
wartrax13/erp_confraria pull request #15
Opened 2021-11-20 20:14 UTC by wartrax13

2021-11-20 20:14 UTC, wartrax13 commented
As variaveis no settings precisam ser consertadas.

2021-11-20 20:37 UTC, wartrax13 commented
close #14

2021-11-20 21:03 UTC, leonextlevel requested changes
correções aí

2021-11-20 21:03 UTC, leonextlevel commented on confraria/urls.py
> +    path('login/', auth_views.LogoutView.as_view(), name='logout'),
login e logout tão com o msm path

2021-11-20 21:03 UTC, leonextlevel commented on confraria/pessoa/views.py
> +class PessoaFisicaCreateView(CreateView, LoginRequiredMixin):
Mixin sempre antes da classe principal

2021-11-21 01:17 UTC, wartrax13 commented on confraria/urls.py
> +    path('login/', auth_views.LogoutView.as_view(), name='logout'),
Realmente kkk

2021-11-21 01:17 UTC, wartrax13 commented on confraria/urls.py
> +    path('login/', auth_views.LogoutView.as_view(), name='logout'),
Realmente. Vou alterar, mas ainda não vou criar um template pra o logout. Vamos ver juntos.

2021-11-21 13:26 UTC, leonextlevel approved these changes

2021-11-21 13:27 UTC, merged