Criado filtro para Disponibilidade e Nome
wartrax13/erp_confraria pull request #46
Opened 2021-12-05 19:19 UTC by AlineDominique

Criado filtro para Disponibilidade e Nome

closes #34
![screencapture-127-0-0-1-8000-produto-list-2021-12-05-16_12_25](https://user-images.githubusercontent.com/22527879/144760373-92717c42-b945-4cef-b0fb-b95f9d5c60c8.png)
![screencapture-127-0-0-1-8000-produto-list-2021-12-05-16_12_14](https://user-images.githubusercontent.com/22527879/144760375-02c8c992-0df3-4fcd-9beb-50a7dadc6203.png)

2021-12-06 00:00 UTC, leonextlevel commented on confraria/produto/views.py
> +        produtos = Produto.objects.all()
Usa o super pra pegar os produtos
```python
produtos = super().get_queryset()
````

2021-12-06 00:00 UTC, leonextlevel commented on confraria/produto/views.py
> +            produtos = Produto.objects.filter(id__in=objects_id, nome__icontains=nome_produto)
filtra o queryset que vc já tem:
```python
produtos = produtos.filter()
```
A mesma coisa dos de baixo

2021-12-06 00:00 UTC, leonextlevel commented on confraria/produto/views.py
> +            produtos = Produto.objects.filter(id__in=objects_id, nome__icontains=nome_produto)
Ou pode usar o objecto Q pra fazer o filtro
https://docs.djangoproject.com/en/3.2/topics/db/queries/#complex-lookups-with-q-objects
https://medium.com/@csantosmachado/compondo-querysets-no-django-utilizando-objetos-q-c88bc3f65031

2021-12-07 02:46 UTC, wartrax13 requested changes

2021-12-07 02:46 UTC, wartrax13 commented on confraria/produto/views.py
> +        produtos = produtos.filter(q).order_by("-nome")
Porque '-nome' na lista de produtos?

2021-12-07 11:10 UTC, AlineDominique commented on confraria/produto/views.py
> +        produtos = produtos.filter(q).order_by("-nome")
Alterei para nome_produto

2021-12-07 11:24 UTC, merged